### ISSUE TITLE
i want to fetch one column from array.

### ISSUE THREAD

**Issue by vinita90** [ramsey/array_column#10]
this is my array and i want to fetch only the value of deviceToken ...

Array ( [0] => Parse\ParseObject Object ( [serverData:protected] => Array ( [Public] => 1 [SavedToProfile] => [deviceToken] => 2677d45739c22e2e4b06debd47d7c018095897429f496cbffc736d47675e7d5d [starCount] => 80 [userid] => Parse\ParseUser Object ( [_sessionToken:protected] => [serverData:protected] => Array ( ) [operationSet:protected] => Array ( ) [estimatedData:Parse\ParseObject:private] => Array ( ) [dataAvailability:Parse\ParseObject:private] => Array ( ) [className:Parse\ParseObject:private] => _User [objectId:Parse\ParseObject:private] => PnqfQ5o1eL [createdAt:Parse\ParseObject:private] => [updatedAt:Parse\ParseObject:private] => [hasBeenFetched:Parse\ParseObject:private] => ) [video] => Parse\ParseFile Object ( [name:Parse\ParseFile:private] => tfss-11c9283e-8b16-46d2-9dcd-095a32398393-video.mov [url:Parse\ParseFile:private] => http://files.parsetfss.com/0445aec8-2c25-4ddf-998d-d5d3f4137a98/tfss-11c9283e-8b16-46d2-9dcd-095a32398393-video.mov [data:Parse\ParseFile:private] => [mimeType:Parse\ParseFile:private] => ) [videoDescription] => Akki [videoThumbnil] => Parse\ParseFile Object ( [name:Parse\ParseFile:private] => tfss-5844ea36-c656-42f4-a592-05173ae730d3-img [url:Parse\ParseFile:private] => http://files.parsetfss.com/0445aec8-2c25-4ddf-998d-d5d3f4137a98/tfss-5844ea36-c656-42f4-a592-05173ae730d3-img [data:Parse\ParseFile:private] => [mimeType:Parse\ParseFile:private] => ) [videoTitle] => new video [videoTotalDuretion] => 8.93 [videoUploadedOnMonthAndYear] => May 2015 ) [operationSet:protected] => Array ( ) [estimatedData:Parse\ParseObject:private] => Array ( [Public] => 1 [SavedToProfile] => [deviceToken] => 2677d45739c22e2e4b06debd47d7c018095897429f496cbffc736d47675e7d5d [starCount] => 80 [userid] => Parse\ParseUser Object ( [_sessionToken:protected] => [serverData:protected] => Array ( ) [operationSet:protected] => Array ( ) [estimatedData:Parse\ParseObject:private] => Array ( ) [dataAvailability:Parse\ParseObject:private] => Array ( ) [className:Parse\ParseObject:private] => _User [objectId:Parse\ParseObject:private] => PnqfQ5o1eL [createdAt:Parse\ParseObject:private] => [updatedAt:Parse\ParseObject:private] => [hasBeenFetched:Parse\ParseObject:private] => ) [video] => Parse\ParseFile Object ( [name:Parse\ParseFile:private] => tfss-11c9283e-8b16-46d2-9dcd-095a32398393-video.mov [url:Parse\ParseFile:private] => http://files.parsetfss.com/0445aec8-2c25-4ddf-998d-d5d3f4137a98/tfss-11c9283e-8b16-46d2-9dcd-095a32398393-video.mov [data:Parse\ParseFile:private] => [mimeType:Parse\ParseFile:private] => ) [videoDescription] => Akki [videoThumbnil] => Parse\ParseFile Object ( [name:Parse\ParseFile:private] => tfss-5844ea36-c656-42f4-a592-05173ae730d3-img [url:Parse\ParseFile:private] => http://files.parsetfss.com/0445aec8-2c25-4ddf-998d-d5d3f4137a98/tfss-5844ea36-c656-42f4-a592-05173ae730d3-img [data:Parse\ParseFile:private] => [mimeType:Parse\ParseFile:private] => ) [videoTitle] => new video [videoTotalDuretion] => 8.93 [videoUploadedOnMonthAndYear] => May 2015 ) [dataAvailability:Parse\ParseObject:private] => Array ( [Public] => 1 [SavedToProfile] => 1 [deviceToken] => 1 [starCount] => 1 [userid] => 1 [video] => 1 [videoDescription] => 1 [videoThumbnil] => 1 [videoTitle] => 1 [videoTotalDuretion] => 1 [videoUploadedOnMonthAndYear] => 1 ) [className:Parse\ParseObject:private] => videoListTable [objectId:Parse\ParseObject:private] => I6eEdNLVQN [createdAt:Parse\ParseObject:private] => DateTime Object ( [date] => 2015-05-28 10:43:25 [timezone_type] => 2 [timezone] => Z ) [updatedAt:Parse\ParseObject:private] => DateTime Object ( [date] => 2015-05-29 04:52:28 [timezone_type] => 2 [timezone] => Z ) [hasBeenFetched:Parse\ParseObject:private] => 1 ) )

**Comment by ramsey** [comment]
It's very hard to see your array, but it looks like you're trying to pass an array of objects to `array_column()`, and it doesn't support that.
